### ISSUE TITLE
there is no lane segmentation ?

### ISSUE THREAD

**Issue by Kenneth-X** [nv-tlabs/lift-splat-shoot#27]
I check the nuscenes datasets, but i find there is no lane gt label : [https://www.nuscenes.org/nuscenes#data-annotation](url)
so, i wonder how does it work to train for lane segmentation and modify the code
![image](https://user-images.githubusercontent.com/13057987/165474685-f25bec3f-013c-41d1-a487-24507992cf79.png)

**Comment by gsg213** [comment]
Hi @Kenneth-X,

You are right there isn't a lane segmentation class, in order to find it, you need the **nuScenes Map Expansion** and extract the ground truth from `NuScenesMap`.

You can go to [https://www.nuscenes.org/nuscenes?tutorial=maps](https://www.nuscenes.org/nuscenes?tutorial=maps) and you will find a class called `lane_divider`.

Finally, you will need to adapt the data loader to bring the map section you require.

I hope this helps!
